### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by matthewleon** [redelmann/haskell-distribution#3]
Notes on how to do this here: https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package

(If you'd rather this package not be included in Stackage, could you add a note here for future reference?)

**Comment by redelmann** [comment]
Hi! Thanks for the interest. I will look into this soon. Cheers!

**Comment by redelmann** [comment]
Pull request on the stackage repository: https://github.com/fpco/stackage/pull/2289

**Comment by redelmann** [comment]
The package is now available on stackage!
